-- 创建文章表
CREATE TABLE IF NOT EXISTS my_nest_admin.articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  summary VARCHAR(500),
  cover VARCHAR(255),
  category VARCHAR(100),
  tags VARCHAR(255),
  status TINYINT DEFAULT 1,
  viewCount INT DEFAULT 0,
  author VARCHAR(100),
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  publishTime TIMESTAMP NULL
);

-- 创建轮播图表
CREATE TABLE IF NOT EXISTS my_nest_admin.banners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  url VARCHAR(255),
  weight INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建友情链接表
CREATE TABLE IF NOT EXISTS my_nest_admin.links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  logo VARCHAR(255),
  description VARCHAR(255),
  weight INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  views INT DEFAULT 0,
  categoryId INT,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleteTime TIMESTAMP NULL
);

-- 创建友情链接分类表
CREATE TABLE IF NOT EXISTS my_nest_admin.link_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255),
  weight INT DEFAULT 0,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 